### ISSUE TITLE
No Globals!

### ISSUE THREAD

**Issue by BasPieren** [RobinStut/web-app-from-scratch-18-19#2]
It's a bad practice to put variables into your global scope. This can cause conflicts with other code which your code gets merged with.

https://github.com/RobinStut/web-app-from-scratch-18-19/blob/b7b0b641a82c190dcfe237fd9435718377afe09b/week1/public/js/app.js#L1

https://github.com/RobinStut/web-app-from-scratch-18-19/blob/b7b0b641a82c190dcfe237fd9435718377afe09b/week1/public/js/app.js#L2

For now it may be a good idea to put all your code inside a IIFE which looks like this:

```js
(function(){

Your code goes here.

})()
```
This way your code still runs immediately but cant be accessed by outside sources.

**Comment by maanlamp** [comment]
@BasPieren ⚠️ Please don't just wrap IIFE's around scopes to enclose them... think about _why_ you needed those variables there in the first place. Do they need to be global? Are you using them only inside a function? Can you pass them as arguments?

Only if all else fails you can think of wrapping it. Don't just do it for the sake of it.

**Comment by BasPieren** [comment]
@maanlamp Fair enough, thanks for the explanation I will remeber it in the future. 👍🏻
