### ISSUE TITLE
ForEach ipv for loop

### ISSUE THREAD

**Issue by MonikaaS** [RobinStut/web-app-from-scratch-18-19#3]
Ik zou op deze regel een forEach gebruiken, zo is je code beter leesbaar.

https://github.com/RobinStut/web-app-from-scratch-18-19/blob/b7b0b641a82c190dcfe237fd9435718377afe09b/week1/public/js/app.js#L18

**Comment by maanlamp** [comment]
Of [`for..of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of)
of [`for..in`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of)

**Comment by RobinStut** [comment]
Thanks for the help! 
`pokeAPI.results.forEach(function(item) {
console.log(item);
}`
